language: java

jdk:
  - openjdk21

dist: jammy

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - develop
    - master

before_install:
  - chmod +x mvnw

install:
  - ./mvnw -B clean compile

script:
  - ./mvnw -B test
  - ./mvnw -B package

after_success:
  - echo "Build y pruebas ejecutadas correctamente"

after_failure:
  - echo "Falló la compilación o las pruebas"
