quarkus.http.port=8080
quarkus.application.name=pennycheck

mp.openapi.extensions.smallrye.info.title=PennyCheck API
mp.openapi.extensions.smallrye.info.version=0.0.1-SNAPSHOT
mp.openapi.extensions.smallrye.info.description=API base para Bank Account Verification con Circulo de Credito

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui

# Cliente REST - sandbox swagger
quarkus.rest-client.circle-credit-api.url=https://services.circulodecredito.com.mx
quarkus.rest-client.circle-credit-api.connect-timeout=5000
quarkus.rest-client.circle-credit-api.read-timeout=10000

# Seguridad base - placeholder
pennycheck.webhook.token=change-me

